### ISSUE TITLE
redmine status afret git push

### ISSUE THREAD

**Issue by grawerpl** [jongha/redmine_vote#13]
after 3 days I get plug-in work (the best part is that plug-in need to work properly libssh2-dev on ubuntu).
Now i have issu witch **git push**

`````` remote:
remote: Notifying Redmine about changes to this repository : 'client-service-app/' ...
remote: /srv/git/local/hooks/common/lib/git_hosting/http_helper.rb:54:in `build_post_request': undefined method `request
_uri' for #<URI::Generic:0x00000001b365e0> (NoMethodError)
remote:         from /srv/git/local/hooks/common/lib/git_hosting/http_helper.rb:10:in `http_post'
remote:         from /srv/git/local/hooks/common/lib/git_hosting/post_receive.rb:33:in `notify_redmine'
remote:         from /srv/git/local/hooks/common/lib/git_hosting/post_receive.rb:19:in `exec'
remote:         from hooks/post-receive:15:in `<main>'```

The best part is that in repository is everything OK (branch, commits, etc.) but redmine still show old info
``````

**Comment by grawerpl** [comment]
wrong repo :D
