### ISSUE TITLE
Application not accessible after plugin installation

### ISSUE THREAD

**Issue by u2rajk** [jongha/redmine_vote#8]
I've installed the plugin, the rake was successful.
Migrating redmine_vote (Redmine Vote plugin)...

But when I open the application, it shows "Internal Error" page, when I go into production log, I could find below lines,

ActionView::Template::Error (Missing partial vote/view_layouts_base_content with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb]}. Searched in:
   "C:/Bitnami/redmine-2.6.1-1/apps/redmine/htdocs/app/views"
):
    56:         <%= view_layouts_base_sidebar_hook_response %>
    57:     </div>
    58: 
    59:     <div id="content">
    60:         <%= render_flash_messages %>
    61:         <%= yield %>
    62:         <%= call_hook :view_layouts_base_content %>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/layouts/base.html.erb:59:in `_app_views_layouts_base_html_erb___608791416_34156752'
  app/controllers/application_controller.rb:466:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:464:in `render_error'
  app/controllers/application_controller.rb:452:in `render_404'
  app/controllers/application_controller.rb:476:in `missing_template'

can you please help me in resolving this? This is very important for me to make it work.

Thanks a lot in advance

Regards,
Raj Kumar

**Comment by artur-w** [comment]
Try changing directory name in "plugins" to "redmine_vote".
